---

- hosts: all
  gather_facts: true
  tasks:
    - name: Grouping!
      become: true
      group_by:
        key: "{{ ansible_os_family }}"


#############  THIS AREA TO STOP ANY SERVICES OR APPS PRIOR TO PATCH ##############


    - name: Stopping UNMS Services
      command: '~unms/app/unms-cli stop'
      failed_when: no

    - name: Stopping DNS Services
      service:
       name: named
       state: stopped
      failed_when: no

    - name: Stopping VPN Services
      service:
       name: openvpn@server
       state: stopped
      failed_when: no

    - name: Stopping Plex Media Server Services
      service:
       name: plexmediaserver
       state: stopped
      failed_when: no
###################################################################################






############# GENERIC COMMANDS FOR DEBIAN BASED SYSTEMS ######################



- hosts: Debian
  gather_facts: true
  become: yes
  max_fail_percentage: 0
  tasks:

    - name: Clean apt
      apt:
       autoclean: yes

    - name: Patching Debian Systems. BE PATIENT!!!!!!!
      apt:
        name: '*'
        state: latest
        force_apt_get: true
      register: upgraded
      

    - name: Rebooting Debian Servers
      shell: 'sleep 1 && shutdown -r now "Reboot now" && sleep1'
      async: 1
      poll: 0
      become: true
      when: upgraded.changed
      register: reboot


    - name: Waiting for servers to come up.
      wait_for:
       port: 22
       host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
       search_regex: OpenSSH
       delay: 60
      when: reboot.changed
      connection: local
###################################################################################



################################# REDHAT BASED SYSTEMS ############################

- hosts: RedHat
  gather_facts: true
  become: yes
  max_fail_percentage: 0
  tasks:

    - name: Cleaning Yum Cache
      shell: yum clean all
       warn=false

    - name: Patching Redhat based systems. BE PATIENT!!!!!!
      yum:
        name: '*'
        state: latest
      register: upgraded

    - name: Rebooting RedHat Servers
      shell: 'sleep 1 && shutdown -r now "Reboot now" && sleep1'
      async: 1
      poll: 0
      become: true
      when: upgraded.changed
      register: reboot

    - name: Waiting for servers to come up.
      wait_for:
       port: 22
       host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
       search_regex: OpenSSH
       delay: 60
      when: reboot.changed
      connection: local





##################################################################################




################ SECTION DEFINES STARTING APPS OR SERVICES #######################

- hosts: all
  gather_facts: true
  tasks:

    - name: Starting UNMS Services
      become: true
      command: '~unms/app/unms-cli start'
      failed_when: no

    - name: Starting DNS Services
      service:
       name: named
       state: started
      failed_when: no

    - name: Starting VPN Services
      service:
       name: openvpn@server
       state: started
      failed_when: no

    - name: Starting Plex Media Server Services
      service:
       name: plexmediaserver
       state: started
      failed_when: no

